#!/usr/bin/env python
"""
rivt :: Ludicrously simple image merger
"""
from __future__ import print_function

import argparse
from itertools import chain
import sys

from PIL import Image


__version__ = "0.0.1"
__description__ = "Ludicrously simple image merger"
__author__ = "Karol Kuczmarski"
__license__ = "GPLv3"


def main(argv=sys.argv):
    args = parse_argv(argv)

    source_images = list(map(Image.open, args.images))
    result_image = sew(source_images)

    if args.show:
        result_image.show()
    else:
        # TODO(xion): decide on output format based on input formats
        result_image.save(args.output, 'PNG')


def parse_argv(argv):
    parser = argparse.ArgumentParser(
        description=__description__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
        add_help=False)

    parser.add_argument('images', type=str, nargs='+',
                        help="image files to sew together",
                        metavar="IMAGE")

    result_group = parser.add_argument_group(
        "Result", "What to do with resulting image") \
        .add_mutually_exclusive_group()
    result_group.add_argument('-o', '--output',
                              type=argparse.FileType('wb', 0), default='-',
                              help="output the image to file with given name",
                              metavar="OUTPUT")
    result_group.add_argument('-s', '--show',
                              action='store_true', default=False,
                              help="show the resulting image "
                                   "(in a system-specific way)")

    misc_group = parser.add_argument_group("Miscellaneous", "Other options")
    misc_group.add_argument('--version', action='version', version=__version__)
    misc_group.add_argument('-h', '--help', action='help',
                             help="show this help message and exit")

    # get the autogenerated usage string and tweak it a little
    # to exclude the miscellaneous flags which aren't part of a normal usage
    usage = parser.format_usage()
    usage = usage[usage.find(parser.prog):].rstrip("\n")  # remove cruft
    for misc_flag in chain.from_iterable(a.option_strings
                                         for a in misc_group._group_actions):
        usage = usage.replace(" [%s]" % misc_flag, "")
    parser.usage = usage

    return parser.parse_args(argv[1:])


def sew(images):
    max_height = max(img.size[1] for img in images)
    adjusted_sizes = [
        (int(img.size[0] * (img.size[1] / float(max_height))), max_height)
        for img in images]
    total_width = sum(width for width, _ in adjusted_sizes)

    result = Image.new('RGB', (total_width, max_height))

    # TODO(xion): allow to specify resampling filter
    x = 0
    for i, (image, size) in enumerate(zip(images, adjusted_sizes)):
        result.paste(image.resize(size, Image.BILINEAR), (x, 0))
        x += size[0]

    return result


if __name__ == '__main__':
    sys.exit(main() or 0)
